# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: minimal
day_night: true
font: ''
font_size: L

# SEO

site_type: Person
local_business_type: ''
org_name: ''
description: ''
twitter: ''

# Contact (edit or remove options as required)

email: alexander.brenning@uni-jena.de
phone: "+49-3641-9-48850, secretary: -48851"
address:
  street: "<strong>Mail</strong> address: Löbdergraben 32"
  city: Jena
  region: TH
  postcode: '07743'
  country: Germany
  country_code: DE
coordinates:
  latitude: '50.92889'
  longitude: '11.58464'
directions: "Office location: Jentower building, 26th floor"

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization

date_format: '2 Jan 2006'
time_format: '3:04 PM'
address_format: de

# Site features

highlight: true
highlight_languages:
  - r
  - python
  - latex
math: true
diagram: false
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    beitrag: false
show_related:
  page: false
  post: true
  beitrag: true
reading_time: true
section_pager: false
docs_section_pager: true
sharing: false
copyright_license:
  enable: true
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    beitrag: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: true
